project_name:
  prefix: "MyProject"
  suffix: "-{tag_name}"

main_branch: main
github:
  check_draft: false

compile:
  enabled: true
  dir: papers/latex

archive:
  format: zip
  dir: papers/latex/releases

hash_algorithms: [md5, sha256, tree]
sign_hash_algo: sha256

signing:
  sign: true
  sign_mode: file

zenodo:
  api_url: "https://sandbox.zenodo.org/api"
  concept_doi: "432538"

generated_files:
  paper:
    pattern: "{compile_dir}/main.pdf"
    rename: true
    identifier:
      use_as_alternate_identifier: true
      source: file
    publishers:
      file_destination: [github, zenodo]
  project:
    rename: true
    archive: false
    publishers:
      file_destination: [zenodo]
  manifest:
    files: [paper, project]
    archive: false
    commit_info: [sha, date_epoch]
    sign: true
    publishers:
      file_destination: [github, zenodo]

prompt_validation_level: danger

